name: Download Immich Images
on: [workflow_dispatch] # 手动点火模式

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Images
        run: |
          # 利用 GitHub 的超级带宽拉取镜像
          docker pull ghcr.io/immich-app/immich-server:latest
          docker pull ghcr.io/immich-app/immich-machine-learning:latest
          docker pull redis:6.2-alpine
          docker pull postgres:14-alpine
          
          # 揉成一个大包
          docker save -o immich_all.tar ghcr.io/immich-app/immich-server:latest ghcr.io/immich-app/immich-machine-learning:latest redis:6.2-alpine postgres:14-alpine
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: immich-package
          path: immich_all.tar
